# SPDX-FileCopyrightText: 2026 AlgorIT Software Consultancy <https://github.com/algoritnl>
# SPDX-License-Identifier: CC0-1.0

FROM ghcr.io/bemanproject/infra-containers-gcc:latest
RUN emerge --sync && emerge sys-libs/glibc
