# SPDX-FileCopyrightText: 2026 AlgorIT Software Consultancy <https://github.com/algoritnl>
# SPDX-License-Identifier: CC0-1.0

name: CI Test

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-26.04

    strategy:
      fail-fast: false
      matrix:
        preset: [gcc-debug, gcc-release, llvm-debug, llvm-release]

    steps:
      - uses: actions/checkout@v7

      - name: Build and test
        run: cmake --workflow ${{ matrix.preset }}


  lint:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7

      - name: Setup LLVM 21 Toolchain
        uses: ./.github/actions/setup-llvm
        with:
          version: '21'

      - name: Perform static analysis
        run: cmake --workflow llvm-lint


  coverage:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v7

      - name: Setup LLVM 21 Toolchain
        uses: ./.github/actions/setup-llvm
        with:
          version: '21'

      - name: Run coverage and collect
        run: cmake --workflow llvm-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./build/llvm-coverage/coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
